# Generated by Django 4.2.5 on 2025-02-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, max_length=100)),
                ('num_tel', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('avenue', models.CharField(blank=True, max_length=100)),
                ('num_reference', models.CharField(blank=True, max_length=100)),
                ('type_contrat', models.CharField(blank=True, max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('statut_paiement', models.BooleanField(default=False)),
            ],
        ),
    ]
