# Generated by Django 4.2.5 on 2025-02-03 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_paiement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
