# Generated by Django 5.1.6 on 2025-02-19 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_alter_client_sex_alter_client_type_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('num_tel', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('avenue', models.CharField(blank=True, max_length=100)),
                ('num_reference', models.CharField(blank=True, max_length=100)),
                ('type_contrat', models.CharField(choices=[('1', '10$'), ('2', '20$'), ('3', 'Extra +')], max_length=1)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('statut_paiement', models.BooleanField(default=False)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='type_contrat',
            field=models.CharField(choices=[('1', '10$'), ('2', '20$'), ('3', 'Extra +')], max_length=1),
        ),
    ]
