# Generated by Django 5.1.6 on 2025-03-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0004_clienttemp_alter_client_type_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
