# Generated by Django 5.1.6 on 2025-03-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0005_client_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientTemp',
        ),
        migrations.AlterField(
            model_name='client',
            name='statut_paiement',
            field=models.CharField(choices=[('payé', 'Payé'), ('attente', 'En attente de paiement'), ('non_payé', 'Non payé')], default='non_payé', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_contrat',
            field=models.CharField(choices=[('1', '10$'), ('2', '15$'), ('3', '100$'), ('4', '150$'), ('5', '200$'), ('6', '250$'), ('7', '300$'), ('8', '350$'), ('9', '400$'), ('10', '450$'), ('11', '500$'), ('12', '550$'), ('13', '600$'), ('14', '650$'), ('15', '700$'), ('16', '800$'), ('17', '1000$')], max_length=2),
        ),
    ]
