# Generated by Django 5.1.6 on 2025-03-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0007_clienttemp_alter_client_statut_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='statut_paiement',
            field=models.CharField(choices=[('payez', '1'), ('attente_payement', '2'), ('Non_payez', '3')], default=3, max_length=16),
        ),
    ]
