# Generated by Django 5.1.6 on 2025-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0008_alter_client_statut_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='statut_paiement',
            field=models.BooleanField(default=False),
        ),
    ]
